### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by L0rd1k** [L0rd1k/SageStreaming#2]
- [x] Add glfw window support,
- [x] Add opencv video stream decoding.
- [ ] Create qml(qt5) window support (Manager App)
- [ ] Fix decoding speed(FFmpeg)
- [x] Add ImGui.
- [ ] Add CRUD for cameras in ImGUI
            - Deadlock while removing
- [ ] Add Commands handler
- [ ] Add support viewer's aspect ratio
- [ ] Add Encoding interface.
